# Generated by Django 5.1.5 on 2025-02-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_id_42',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
