# Generated by Django 5.1.5 on 2025-02-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_avatar_customuser_oauth_id_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oauth_id_github',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
